---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 29.05.2023 19:58
---

---@param string
---@return number
function FourCC(string)  end

-- prints directly into console
function printc(string) end

-- false: выводит только название карты
-- true: выводит путь от корня варика
---@param fromWar3Root boolean
---@return string
function GetMapFileName(fromWar3Root)  end

---@param path string
function SDoFile(path)
  dofile(EXTERNAL_PATH .. path)
end

---@param path string
---@return any
function SLoadFile(path)
  return loadfile(EXTERNAL_PATH .. path)
end