---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 21.06.2023 16:46
---

---@class handle

---@alias integer number
---@alias real number
---@alias nothing void
---@alias code fun


---@return boolean
function IsDevMode() end