---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 26.11.2022 6:08
---

--------------------------------------------------------------------
-- private logic
--------------------------------------------------------------------

---@param path string
local function CreateFolder(path)
  PreloadGenClear()
  PreloadGenStart()
  Preload("Folder creation with Preloader")
  PreloadGenEnd(path .. "\\temp.temp")
  os.remove(path .. "\\temp.temp")
end


---@param path string
local function CheckFolderPath(path)
  --printdf("check folder path: %s", path)
  CreateFolder(path)
end

---@param filename string
---@return string
local function CheckFileName(filename)
  --if no filename provided
  --if filename contains only spaces

  if(filename == nil or string.match(filename, "%S") == nil)then
    filename = tostring(os.date("%Hh%Mm%Ss %dd%mm%Yy"))
  end

  return filename
end

---@param player player
---@param path string
---@param filename string
---@param content string
---@return boolean
local function WriteFile(player, path, filename, content)
  local file

  CheckFolderPath(path)
  filename = CheckFileName(filename)

  if(IsDevMode() == false)then
    Logger.SendInfoLocal(player,"dev mode is not enabled, saving into file may not work ")
  end

  file = io.open(path .. "\\" .. filename .. ".txt","w+")

  if(file == nil)then
    Logger.SendInfoLocal(player,"file cannot be opened")
    return false
  end



  --io.output(file) --nil
  --io.write(content)
  --file:close()

  file:write(content)
  file:close()

  return true
end


---@param path string
---@param filename string
---@return boolean, string
local function ReadFile(path, filename)
  local file, content

  file = io.open(path .. "\\" .. filename .. ".txt","r")

  if(file == nil)then
    printd("File is empty or not exist")
    return false, nil
  end

  content = file:read("*all")
  file:close()

  return true, content
end

--------------------------------------------------------------------
-- public functions
--------------------------------------------------------------------

DriveAccessor = {
  WriteFile = WriteFile,
  ReadFile = ReadFile,
}