---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 26.11.2022 6:08
---

---@param path string
local function CreateFolder(path)
  PreloadGenClear()
  PreloadGenStart()
  Preload("Folder creation with Preloader")
  PreloadGenEnd(path .. "\\temp.temp")
  os.remove(path .. "\\temp.temp")
end


---@param path string
local function CheckFolderPath(path)
  --printdf("check folder path: %s", path)
  CreateFolder(path)
end

---@param filename string
---@return string
local function CheckFileName(filename)
  --if no filename provided
  --if filename contains only spaces

  if(filename == nil or string.match(filename, "%S") == nil)then
    filename = tostring(os.date("%Hh%Mm%Ss %dd%mm%Yy"))
  end

  return filename
end

---@param player player
---@param path string
---@param filename string
---@param content string
---@return boolean
local function WriteFile(player, path, filename, content)
  CheckFolderPath(path)
  filename = CheckFileName(filename)

  local full_path = path .. "\\" .. filename .. ".txt"

  local is_file_exists = TextFileExists(full_path)
  if(is_file_exists)then
    Logger.SendInfoLocal(player,"file with this name exists; file will be overriden!")
  end

  local file = TextFileOpen(full_path)
  TextFileClear(file)
  TextFileWriteLine(file, content)
  TextFileClose(file)

  return true
end


---@param path string
---@param filename string
---@return boolean, string
local function ReadFile(path, filename)
  local full_path = path .. "\\" .. filename .. ".txt"

  if(TextFileExists(full_path) == false)then
    Logger.SendInfo("file not exists")
    return false, nil
  end

  local file = TextFileOpen(full_path)
  local content = TextFileReadAll(file)
  TextFileClose(file)

  if(content == "")then
    Logger.SendInfo("file is empty")
    return false, nil
  end


  return true, content
end

--------------------------------------------------------------------
-- public functions
--------------------------------------------------------------------

DriveAccessor = {
  WriteFile = WriteFile,
  ReadFile = ReadFile,
}