---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 19.06.2023 16:16
---


---@param name string
---@return dialog
function ExDialogCreate(name)
  local d = DialogCreate()
  local trig = CreateTrigger()

  TriggerRegisterDialogEvent(trig, d) -- утекает здесь, как фиксить непонятно
  TriggerAddAction(trig, function()
    local callback = GetObjectData(GetClickedDialog(), GetClickedButton())
    callback()
  end)

  SetObjectData(d, 0, trig)
  DialogSetMessage(d, name)

  return d
end

local function ExDialogDestroy()
  local d = GetClickedDialog()
  local trig = GetObjectData(d, 0)
  DestroyTrigger(trig)
  ClearObjectData(d)
  DialogClear(d)
  DialogDestroy(d)
end

function ExDialogAddButton(dialog, button_name, hotkey, destroyAfterClick, callback)
  local butt = DialogAddButton(dialog, button_name, hotkey)
  SetObjectData(dialog, butt, function()
    callback()
    if(destroyAfterClick)then ExDialogDestroy() end
  end)
end

function ExDialogAddExit(dialog)
  local butt = DialogAddButton(dialog, "Exit [esc]", 0x1B)

  SetObjectData(dialog, butt, ExDialogDestroy)
end