---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 20.06.2023 20:34
---

---@param stat_table orderedTable<statKey, number>
---@return string
local function GenerateDescriptionFromStatTable(stat_table)
  local str = ""

  for stat_key, stat_value in pairs(stat_table)do
    if(stat_value == 0)then goto next end

     str = str .. GetStatDeltaDescription(stat_key, stat_value) .. "\n"

    ::next::
  end

  --str = string.sub(str, 0, #str-2)

  return str
end

--- parses all items with custom stats, generates description for each stat based on stat_definitions.lua
--- and then adds this to existing item description
--- e.g. original description is "blablabla"
--- you will get "blablabla \n ----- \n Урон +25 \n Сила +50"
function Execute_RebuildItemDescriptions()

  local fourcc = fourcc
  local GetBaseItemStringFieldById = GetBaseItemStringFieldById
  local ITEM_SF_TOOLTIP_EXTENDED = ITEM_SF_TOOLTIP_EXTENDED

  for itemid, v in pairs(STATS__ITEM_TABLE)do
    ---@type orderedTable<statKey, number>
    local itemstats = v

    local old_desc = GetBaseItemStringFieldById(fourcc(itemid), ITEM_SF_TOOLTIP_EXTENDED)
    local added = GenerateDescriptionFromStatTable(itemstats)

    SetBaseItemStringFieldById(fourcc(itemid), ITEM_SF_TOOLTIP_EXTENDED, old_desc .. "\n-----\n" .. added)
  end
end