---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 21.06.2023 7:32
---

---@alias ex_player_event integer

---@type ex_player_event
EX_EVENT_PLAYER_LEAVE = malloc()        -- EVENT_PLAYER_LEAVE
---@type ex_player_event
EX_EVENT_PLAYER_CHAT = malloc()         -- EVENT_PLAYER_CHAT

---@type table<ex_player_event, FuncList>
local event_list = NewOrderedTable()

---@param event_type ex_player_event
---@param callback fun():void
function RegisterPlayerExEvent(event_type, callback)
  event_list[event_type] = event_list[event_type] or NewOrderedTable()
  FuncListAdd(event_list[event_type], callback)
end

---@param event_type ex_player_event
---@param callback fun():void
function RemovePlayerExEvent(event_type, callback)
  if(event_list[event_type] == nil)then return end
  FuncListRemove(event_list[event_type], callback)
end

---@param event_type ex_unit_event
local function ExecutePlayerExEvent(event_type)
  if(event_list[event_type] == nil)then return end
  local func_list = event_list[event_type]
  if(func_list == nil) then return end

  FuncListExecute(func_list)
end


---------------------------------------------------------------------------------------------------

local function InitChatTrig()
  local function OnChat()
    --printdf("player %s wrote: %s", GetPlayerName(GetTriggerPlayer()), GetEventPlayerChatString())
    ExecutePlayerExEvent(EX_EVENT_PLAYER_CHAT)
  end

  local trig = CreateTrigger()
  TriggerAddAction(trig, OnChat)

  for i = 0, 15 do
    TriggerRegisterPlayerChatEvent(trig, Player(i), "", false)
  end
end

local function InitLeaveTrig()
  local function OnLeave()
    local p = GetTriggerPlayer()

    Logger.SendInfo("%s has left the game", GetPlayerName(p))
    ExecutePlayerExEvent(EX_EVENT_PLAYER_LEAVE)
  end

  local trig= CreateTrigger()
  TriggerAddAction(trig, OnLeave)

  for i = 0, 15 do
    TriggerRegisterPlayerEvent(trig, Player(i), EVENT_PLAYER_LEAVE)
  end
end

local init_done = false

function Init_PlayerTrigs()
  if(init_done)then return end

  InitChatTrig()
  InitLeaveTrig()

  init_done = true
end