---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 17.06.2023 20:52
---

---@type table<string, table<ex_item_event, fun():void>>
local func_list = {}

--- automatically adds this callback to given event when item equipped
--- and removed callback when item is dropped
--- todo: test if it works correctly if item gets removed from inventory (can it skip drop trig)
---@param itemid integer | string
---@param event_type ex_unit_event
---@param callback fun():void
function RegisterCallbackOnUnitEventOnItem(itemid, event_type, callback)
  local itemid = fourci(itemid)

  func_list[itemid] = func_list[itemid] or {}
  func_list[itemid][event_type] = callback
end


---@param u unit
---@param itemid integer|string
local function AddUnitEvent(u, itemid)

  ---@type table<ex_item_event, fun():void>
  local item_events = func_list[fourci(itemid)]
  if(item_events == nil) then return end

  for event_type, func in pairs(item_events)do
    RegisterUnitExEvent(u, event_type, func)
  end
end

---@param u unit
---@param itemid integer|string
local function RemoveUnitEvent(u, itemid)
  ---@type table<ex_item_event, fun():void>
  local item_events = func_list[fourci(itemid)]
  if(item_events == nil) then return end

  for event_type, func in pairs(item_events)do
    RemoveUnitExEvent(u, event_type, func)
  end
end


local is_inited = false
function Init_CallbacksOnUnitEventOnItems()
  if(is_inited)then return end

  local function OnPickup()
    AddUnitEvent(GetManipulatingUnit(), GetItemTypeId(GetManipulatedItem()))
  end
  RegisterEvent(EVENT_PLAYER_UNIT_PICKUP_ITEM, OnPickup)

  local function OnDrop()
    RemoveUnitEvent(GetManipulatingUnit(), GetItemTypeId(GetManipulatedItem()))
  end
  RegisterEvent(EVENT_PLAYER_UNIT_DROP_ITEM, OnDrop)

  is_inited = true
end

---------------------------------------------------------------------------------------------------