---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 20.06.2023 13:38
---

---@shape lootInstance
---@field chance number
---@field itemid string
---@field show_text boolean

---@type table<string, lootInstance[]>
local loot_list = {}


---@param unitid string
---@param itemid string
---@param drop_chance number
function RegisterUnitLoot(unitid, itemid, drop_chance)
  unitid = fourci(unitid)
  loot_list[unitid] = loot_list[unitid] or NewOrderedTable()

  ---@type lootInstance
  local loot_instance = {
    chance = drop_chance,
    itemid = itemid,
    show_text = false,
  }

  table.insert(loot_list[unitid], loot_instance)
end


---@param unitid string
---@param itemid string
---@param drop_chance number
function RegisterUnitLootWithText(unitid, itemid, drop_chance)
  unitid = fourci(unitid)
  loot_list[unitid] = loot_list[unitid] or NewOrderedTable()

  ---@type lootInstance
  local loot_instance = {
    chance = drop_chance,
    itemid = itemid,
    show_text = true
  }

  table.insert(loot_list[unitid], loot_instance)
end

---------------------------------------------------------------------------------------------------

---@param u unit
---@param str string
local function CreateLootText(u, str)
  local x, y, z = GetUnitX(u), GetUnitY(u), GetUnitZ(u)+25

  local tt = CreateTextTag()
  SetTextTagText(tt,str,.045)
  SetTextTagPos(tt,x,y,z)
  SetTextTagVisibility(tt,true)
  SetTextTagPermanent(tt,false)
  SetTextTagLifespan(tt,3)
  SetTextTagFadepoint(tt,2)
  SetTextTagVelocity(tt, 0.02*Cos(bj_PI/3),0.03*Sin(bj_PI/2))
end


---@param unit unit
---@param loot lootInstance[]
local function CreateLoot(unit, loot)
  local x, y = GetUnitX(unit), GetUnitY(unit)

  ---@type string[]
  local items_with_text = --[[---@type string[] ]] NewOrderedTable()

  for _, instance in pairs(loot)do
    if(GetRandomReal(0., 99.) >= instance.chance)then goto next end

    local itemid = instance.itemid
    CreateItem(fourcc(itemid), x, y)

    if(instance.show_text)then
      table.insert(items_with_text, itemid)
    end

    ::next::
  end

  if(#items_with_text == 0)then return end

  local item_names = NewOrderedTable()
  for _, v in pairs(items_with_text)do
    table.insert(item_names, ItemIdToItemName(v))
  end

  local format = string.rep("%s, ", #items_with_text)
  format = string.sub(format, 0, #format-2)

  local str = string.format(format, table.unpack(item_names))
  str = str .. " dropped!"

  CreateLootText(unit, str)

end

function Init_UnitLoot()
  local function OnDeath()
    local unit = GetDyingUnit()
    local unitid = fourci(GetUnitTypeId(unit))
    local l_i = loot_list[unitid]
    if(l_i == nil)then return end

    CreateLoot(unit, l_i)
  end

  RegisterEvent(EVENT_PLAYER_UNIT_DEATH, OnDeath)
end