---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 18.06.2023 23:15
---

SDoFile("content\\part0.lua")
SDoFile("content\\part1.lua")
SDoFile("content\\part2.lua")
SDoFile("content\\part3.lua")
SDoFile("content\\part4.lua")
SDoFile("content\\part5.lua")
SDoFile("content\\part6.lua")
SDoFile("content\\part7.lua")
SDoFile("content\\part8.lua")
SDoFile("content\\part9.lua")
SDoFile("content\\part10.lua")
SDoFile("content\\part11.lua")
SDoFile("content\\part12.lua")

function Init_Content()
  Part_0_Init()
  Part_1_Init()
  Part_2_Init()
  Part_3_Init()
  Part_4_Init()
  Part_5_Init()
  Part_6_Init()
  Part_7_Init()
  Part_8_Init()
  Part_9_Init()
  Part_10_Init()
  Part_11_Init()
  Part_12_Init()
end