---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 18.06.2023 23:57
---

local function Item_I002_Init()
  local id = "I002"

  RegisterItemExEvent(id, EX_EVENT_ITEM_PAWN, function()
    Logger.SendInfoLocal(GetOwningPlayer(GetSellingUnit()), "item was sold, so another one is created")
    CreateItem(fourcc(id), -1350, 1850)
  end)

end


local function Item_I003_Init()
  local id = "I003"

  RegisterItemExEvent(id, EX_EVENT_ITEM_SELL, function()
    Logger.SendInfoLocal(GetOwningPlayer(GetBuyingUnit()), "item was bought in shop!")
  end)

  RegisterItemExEvent(id, EX_EVENT_ITEM_DROP, function()
    Logger.SendInfoLocal(GetOwningPlayer(GetManipulatingUnit()), "item was dropped and will be removed!")

    -- without timer it spawns [Lua ERROR]: cannot resume non-suspended coroutine
    -- ask ev3nt about that
    local it = GetManipulatedItem()
    TimerStartSingle(0, function()
      RemoveItem(it)
    end)
  end)

end

function Part_3_Init()
  Item_I002_Init()
  Item_I003_Init()
end

