---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 18.06.2023 23:57
---

local function Item_I00F_Init()
  local id = "I00F"

  RegisterItemInitCallback(id, function()
    SetBaseItemStringFieldById(fourcc(id), ITEM_SF_TOOLTIP_NORMAL, "Unit Respawn and Loot")
    SetBaseItemStringFieldById(fourcc(id), ITEM_SF_TOOLTIP_EXTENDED,
      "Shows the power of scripting!"
      .. "\nSmoll angry stone, which respawns in 4 seconds!"
      .. "\nloot:"
      .. "\n75%: claws of attack +3"
      .. "\n75%: claws of attack +6"
      .. "\n75%: claws of attack +9 - shown with text"
      .. "\n75%: orb of shadows +10 - shown with text"
      .. "\nthis item also enables missing unitstats warns while in inventory"
    )

    SetBaseItemStringFieldById(fourcc(id), ITEM_SF_NAME, "Part 9")
    SetBaseItemStringFieldById(fourcc(id), ITEM_SF_DESCRIPTION, "Unit Respawn and Loot")
  end)

  RegisterItemExEvent(id, EX_EVENT_ITEM_PICKUP, function()
    Logger.SendInfo("unitstat warns enabled")
    ShowUnitstatWarns(true)
  end)

  RegisterItemExEvent(id, EX_EVENT_ITEM_DROP, function()
    Logger.SendInfo("unitstat warns disabled")
    ShowUnitstatWarns(false)
  end)

end

local function Unit_e001_Init()
  local id = "e001"

  RegisterDefaultUnitStats_A(id, 25, 5, 100, 10, 10, 0.1, 350)
  RegisterDefaultUnitStats_B(id, 0, 0, 0)
  RegisterDefaultUnitStats_C(id, 2)

  RegisterUnitTypeRespawnTime(id, 4)

  RegisterUnitLoot(id, "rat3", 75)
  RegisterUnitLoot(id, "rat6", 75)
  RegisterUnitLootWithText(id, "rat9", 75)
  RegisterUnitLootWithText(id, "sora", 75)
end

function Part_9_Init()
  Unit_e001_Init()
  Item_I00F_Init()
end

