---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 18.06.2023 23:57
---

local function Chat_PrintSelectedUnitStats(player, _)
  local u = GetUnitSelected(player)
  if(u == nil)then
    Logger.SendDebugLocal(player, "you have nothing selected")
    return
  end

  local stat_copy = GetUnitStatCopy(u)

  local s_begin = string.format("showing stats of %s", GetUnitName(u))
  local s_end = "end"
  local str = ""
  local separator = ";    "

  for stat_key, value in pairs(stat_copy)do
    str = str .. GetStatValueDescription(stat_key, value) .. separator
  end
  str = string.sub(str, 0, #str-#separator)
  str = string.format("%s\n%s\n%s", s_begin, str, s_end)

  Logger.SendInfoLocal(player, str)
end


---@param player player
---@param args string
local function Chat_Fourcc(player, args)
  -- input: A000
  -- expected output: fourcc(A000) = 1093677104
  Logger.SendDebug("fourcc(%s) = %s", args, fourcc(args))
end


---@param player player
---@param args string
local function Chat_Fourci(player, args)
  -- input: 1093677104
  -- expected output: fourcc(1093677104) = A000

  -- tonumber because originally thats a string containing number, so it not converts it
  Logger.SendDebug("fourci(%s) = %s", args, fourci(tonumber(args)))
end


---@param player player
---@param args string
local function Chat_PrintSelectedUnit(player, args)
  local u = GetUnitSelected(player)
  Logger.SendInfo("%s is selected by %s", GetUnitName(u), GetPlayerName(player))
end


local function Chat_GetUnitInfo(player, args)
  local u = GetUnitSelected(player)
  if(u == nil)then
    Logger.SendDebugLocal(player, "you have nothing selected")
    return
  end

  Logger.SendInfoLocal(player, "unit stats\n %s | %s | %s", fourci(GetUnitTypeId(u)), GetUnitName(u), GetHandleId(u))
end


local function Init_ChatCommands()
  ChatCommandList.AddCommand(ChatCommandList.PrintAll, "prints all commands in chat", {"-cmd", "-show all commands"})
  ChatCommandList.AddCommand(Chat_PrintSelectedUnit, "prints name of selected unit", {"-print unit name", "-pun", "-p u n"})

  ChatCommandList.AddCommand(Chat_Fourcc, "converts id to fourcc, string -> int", {"-fourcc", "-fcc"})
  ChatCommandList.AddCommand(Chat_Fourci, "converts id to fourci, int -> string", {"-fourci", "-fci"})

  ChatCommandList.AddCommand(Chat_PrintSelectedUnitStats, "prints stats of selected unit", {"-show stats", "-ss"})

  ChatCommandList.AddCommand(Chat_GetUnitInfo, "prints basic info of selected unit", {"-unitinfo"})
end


function Part_11_Init()
  Init_ChatCommands()
end

