---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 18.06.2023 23:57
---

local chest1, chest2


local function InitAdvancedCrafting()
  local id = "I00A"

  RegisterItemExEvent(id, EX_EVENT_ITEM_PICKUP, function()
    local rune = GetManipulatedItem()
    local u = GetManipulatingUnit()

    -- get all items from hero and from all chests

    ---@type unit[]
    local unit_list = {u, chest1, chest2}

    local item_list = {}
    for _, unit in pairs(unit_list)do
      for i = 0, 5 do
        local item = UnitItemInSlot(unit, i)
        if(item ~= nil)then
          table.insert(item_list, item)
        end
      end
    end

    ShowCraftingDialog2(u, item_list)

    TimerStartSingle(0, function()
      RemoveItem(rune)        -- рунка утекает, почему - непонятно
    end)
  end)
end


local function InitRecipes()
  local id_s = "I00B"
  local id_m = "I00C"
  local id_b = "I00D"

  RegisterCraftRecipe(id_m, id_s, id_s)
  RegisterCraftRecipe(id_b, id_m, id_m)
end


local function FillChests()
  for i = 0, 3 do
    local u = i <= 1 and chest1 or chest2
    local it = CreateItem(fourcc("I00B"), 0, 0)
    UnitAddItem(u, it)
    SetItemDroppable(it, false)
    DestroyEffect(AddSpecialEffectTarget("Abilities\\Spells\\Human\\Resurrect\\ResurrectCaster.mdl", u, "origin"))
  end
end


local function InitChests()
  local id = "h003"
  local id_c = fourcc(id)

  chest1 = CreateUnit(Player(0), id_c, 630, 1925, 300)
  chest2 = CreateUnit(Player(0), id_c, 630, 1825, 300)

  FillChests()
end


local function Item_I00D_Init()
  local id = "I00D"

  RegisterItemExEvent(id, EX_EVENT_ITEM_DROP, function()
    FillChests()

    local it = GetManipulatedItem()
    TimerStartSingle(0, function()
      RemoveItem(it)
    end)
  end)

end


function Part_7_Init()
  InitAdvancedCrafting()
  InitRecipes()
  InitChests()
  Item_I00D_Init()
end

