---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 18.06.2023 23:57
---

local blink_id = fourcc("A002")

local function Item_I000_Init()
  local id = "I000"

  RegisterItemAttach(id, "Abilities\\Spells\\Human\\MassTeleport\\MassTeleportTo.mdl", "origin")

  RegisterItemInitCallback(id, function()
    SetBaseItemStringFieldById(fourcc(id), ITEM_SF_TOOLTIP_NORMAL, "Teleportation Stone")
    SetBaseItemStringFieldById(fourcc(id), ITEM_SF_TOOLTIP_EXTENDED, "Adds teleport effect to unit \'origin\' while in inventory\nAlso adds blink ability")

    SetBaseItemStringFieldById(fourcc(id), ITEM_SF_NAME, "Part 1 - Item with attachment")
    SetBaseItemStringFieldById(fourcc(id), ITEM_SF_DESCRIPTION, "Teleportation Stone")
  end)

  RegisterItemExEvent(id, EX_EVENT_ITEM_PICKUP, function()
    -- blink ability to shorten test time
    UnitAddAbility(GetManipulatingUnit(), blink_id)
  end)

  RegisterItemExEvent(id, EX_EVENT_ITEM_DROP, function()
    -- blink ability to shorten test time
    UnitRemoveAbility(GetManipulatingUnit(), blink_id)
  end)
end

local function CreateItems()
  local id = "I000"
  TimerStartSingle(2, function() CreateItem(id, -2300, 1815) end)
end

function Part_1_Init()
  Item_I000_Init()
  CreateItems()
end