---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 18.06.2023 12:51
---

---@type table<statKey, number>
local default_percent_stats = --[[---@type table<statKey, number ]] NewOrderedTable()
default_percent_stats[STAT_KEY_DAMAGE_PERCENT] = 100
default_percent_stats[STAT_KEY_ARMOUR_PERCENT] = 100
default_percent_stats[STAT_KEY_LIFE_PERCENT] = 100
default_percent_stats[STAT_KEY_MANA_PERCENT] = 100
default_percent_stats[STAT_KEY_LIFE_REGEN_PERCENT] = 100
default_percent_stats[STAT_KEY_MANA_REGEN_PERCENT] = 100
default_percent_stats[STAT_KEY_MOVE_SPEED_PERCENT] = 100
default_percent_stats[STAT_KEY_STR_PERCENT] = 100
default_percent_stats[STAT_KEY_AGI_PERCENT] = 100
default_percent_stats[STAT_KEY_INT_PERCENT] = 100
default_percent_stats[STAT_KEY_ATTACKSPEED_PERCENT] = 100
default_percent_stats[STAT_KEY_DPS_PERCENT] = 100


---@type table<statKey, number>
local default_base_stats_template = --[[---@type table<statKey, number ]]  NewOrderedTable()

default_base_stats_template[STAT_KEY_DAMAGE] = 10
default_base_stats_template[STAT_KEY_ARMOUR] = 1
default_base_stats_template[STAT_KEY_LIFE] = 100
default_base_stats_template[STAT_KEY_MANA] = 100
default_base_stats_template[STAT_KEY_LIFE_REGEN] = 10
default_base_stats_template[STAT_KEY_MANA_REGEN] = 10
default_base_stats_template[STAT_KEY_MOVE_SPEED] = 250
default_base_stats_template[STAT_KEY_STR] = 0
default_base_stats_template[STAT_KEY_AGI] = 0
default_base_stats_template[STAT_KEY_INT] = 0
default_base_stats_template[STAT_KEY_BASE_ATTACKSPEED] = 1.5
default_base_stats_template[STAT_KEY_DPS] = 10


---@type orderedTable<string, table<statKey, number>>
DEFAULT_UNIT_STATS = NewOrderedTable()


local do_show_warns = true

---@param format string
---@vararg string | any
local function ShowWarn(format, ...)
  if(do_show_warns == false)then return end

  Logger.SendDebug(format, ...)
end

---@param flag boolean
function ShowUnitstatWarns(flag)
  do_show_warns = flag
end


---@param u unit
function ApplyDefaultUnitStats(u)
  local unitid = fourci(GetUnitTypeId(u))
  STATS__UNIT_TABLE[u] = STATS__UNIT_TABLE[u] or NewOrderedTable()

  ---@type table<statKey, number>
  local d_s = DEFAULT_UNIT_STATS[unitid]

  --Logger.SendDebug("ApplyDefaultUnitStats: processing unit %s | %s | %s", fourci(GetUnitTypeId(u)), GetUnitName(u), GetHandleId(u))

  if(d_s == nil)then
    ShowWarn("unit %s | %s | %s has no registered stats at all, applying all stats from template", fourci(GetUnitTypeId(u)), GetUnitName(u), GetHandleId(u))
    d_s = default_base_stats_template
  end

  -- normal stats
  for stat_key, def_value in pairs(default_base_stats_template)do
    local value = d_s[stat_key]

    if(value == nil)then
      ShowWarn("unit %s | %s | %s has no registered stat %s, using default: %s", fourci(GetUnitTypeId(u)), GetUnitName(u), GetHandleId(u), GetStatName(stat_key), def_value)
      value = def_value
    end

    STATS__UNIT_TABLE[u][stat_key] = value
  end

  -- percent stats
  for stat_key, val in pairs(default_percent_stats)do
    STATS__UNIT_TABLE[u][stat_key] = val
  end

  UpdateUnitStatsForced(u)
end


function Init_InitialUnitStats()
  local G = CreateGroup()
  GroupEnumUnitsInRange(G, 0, 0, 99999, nil)
  local n = GroupGetCount(G)

  for i = 0, n-1 do
    local u =  GroupGetUnitByIndex(G, i)
      ApplyDefaultUnitStats(u)
  end

  GroupClear(G)
  DestroyGroup(G)
end

---------------------------------------------------------------------------------------------------

---@param unitid integer|string
---@param damage number
---@param armour number
---@param life number
---@param mana number
---@param life_regen number
---@param mana_regen number
---@param move_speed number
function RegisterDefaultUnitStats_A(unitid, damage, armour, life, mana, life_regen, mana_regen, move_speed)
  local unitid = fourci(unitid)

  DEFAULT_UNIT_STATS[unitid] = DEFAULT_UNIT_STATS[unitid] or NewOrderedTable()

  DEFAULT_UNIT_STATS[unitid][STAT_KEY_DAMAGE] = damage
  DEFAULT_UNIT_STATS[unitid][STAT_KEY_ARMOUR] = armour
  DEFAULT_UNIT_STATS[unitid][STAT_KEY_LIFE] = life
  DEFAULT_UNIT_STATS[unitid][STAT_KEY_MANA] = mana
  DEFAULT_UNIT_STATS[unitid][STAT_KEY_LIFE_REGEN] = life_regen
  DEFAULT_UNIT_STATS[unitid][STAT_KEY_MANA_REGEN] = mana_regen
  DEFAULT_UNIT_STATS[unitid][STAT_KEY_MOVE_SPEED] = move_speed


  RegisterUnitExEvent2_IgnoreDuplicates(unitid, EX_EVENT_UNIT_C_CREATED, ApplyDefaultUnitStats)
end


---@param unitid integer|string
---@param str number
---@param agi number
---@param int number
function RegisterDefaultUnitStats_B(unitid, str, agi, int)
  local unitid = fourci(unitid)

  DEFAULT_UNIT_STATS[unitid] = DEFAULT_UNIT_STATS[unitid] or NewOrderedTable()

  DEFAULT_UNIT_STATS[unitid][STAT_KEY_STR] = str
  DEFAULT_UNIT_STATS[unitid][STAT_KEY_AGI] = agi
  DEFAULT_UNIT_STATS[unitid][STAT_KEY_INT] = int

  RegisterUnitExEvent2_IgnoreDuplicates(unitid, EX_EVENT_UNIT_C_CREATED, ApplyDefaultUnitStats)
end

---@param unitid integer|string
---@param base_as_cd number
function RegisterDefaultUnitStats_C(unitid, base_as_cd)
  local unitid = fourci(unitid)

  DEFAULT_UNIT_STATS[unitid] = DEFAULT_UNIT_STATS[unitid] or NewOrderedTable()

  DEFAULT_UNIT_STATS[unitid][STAT_KEY_BASE_ATTACKSPEED] = base_as_cd

  RegisterUnitExEvent2_IgnoreDuplicates(unitid, EX_EVENT_UNIT_C_CREATED, ApplyDefaultUnitStats)
end

