---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 15.06.2023 6:23
---

--InitDebugHooks()

SDoFile("libs\\modules\\Benchmark.lua")
SDoFile("libs\\modules\\Logger.lua")
--
SDoFile("libs\\basic.lua")
--
SDoFile("libs\\modules\\OrderedTable.lua")
SDoFile("libs\\low_level.lua")
--
SDoFile("libs\\modules\\FuncList.lua")
--
SDoFile("libs\\abils.lua")
SDoFile("libs\\items.lua")
SDoFile("libs\\units.lua")
SDoFile("libs\\players.lua")
--
SDoFile("libs\\modules\\ChatCommandList.lua")
--
SDoFile("libs\\unit_events_on_items.lua")
--
SDoFile("libs\\stats\\stats.lua")
SDoFile("libs\\stats\\stat_definitions.lua")
SDoFile("libs\\stats\\itemstats.lua")
SDoFile("libs\\stats\\unitstats.lua")
SDoFile("libs\\stats\\stat_dps.lua")
--
SDoFile("libs\\ex_dialog.lua")
--
SDoFile("libs\\modules\\saveloader\\saveloader.lua")
--
SDoFile("libs\\crafts.lua")
--
SDoFile("libs\\unit_respawn.lua")
SDoFile("libs\\unit_loot.lua")
--
SDoFile("libs\\item_description.lua")
--
SDoFile("content\\content.lua")


TimerStart(CreateTimer(), 1, false, function()
  Init_AbilityTrigs()                             -- abils.lua
  Init_ItemTrigs()                                -- items.lua
  Init_UnitTrigs()                                -- units.lua
  Init_PlayerTrigs()                              -- players.lua
  --
  Init_CallbacksOnUnitEventOnItems()              -- unit_events_on_items.lua
  Init_ItemStatUpdater()                          -- itemstats.lua
  ChatCommandList.Init()                          -- chatCommandList.lua
  --
  Saveloader.Init()                               -- saveloader.lua
  Init_UnitLoot()                                 -- unit_loot.lua
  Init_UnitRespawn()                              -- unit_respawn.lua
  --
  ShowUnitstatWarns(false)
  Init_Content()                                  -- content folder
  --
  -- should be called after all unit stat will be registered in InitContent
  Init_InitialUnitStats()                         -- unitstats.lua
  --
  Execute_UnitInitList()                          -- units.lua
  Execute_ItemInitList()                          -- items.lua
  Execute_AbilityInitList()                       -- abils.lua
  Execute_RebuildItemDescriptions()               -- item_description.lua
  --
  ExecuteFuncForAllInitialUnits()                 -- low_level.lua
  --

  --[[
  команды чата - более компактный вид отображения?

  RegisterItemEquipRequirements?
    item equip requirements callback(unit, item)?
      if callback(...) == false then -> DropItem instantly?
  ]]

end)

--[[
система задумывается как более или менее модульная,
т.е. вы можете не пользоваться ненужными либами или вообще убрать их


есть прописанный разрабом карты unitid и его статы

при создании юнита мы перезаписываем эти статы в юнита т.е. овеердайд РО даты
также могут быть непрописанные юниты, которые сделаны в РО и не добавлены или ещё какая срань
как поступать с ними

а) при создании применять дефолтные статы + выкидывать ошибку
б) при создании не трогать, но при взаимодействии накидывать дефолтные статы + выкидывать ошибку
в) парсить их статы в рантайме и создавать таблицу статов по их текущим статам (плюс дохуя геттеров как кода)

суть модуля статов именно в прописывании статов всяким unitid через код
т.е. если ты забыл когото добавить = обосрался сам как разраб


не проси чтобы разраб сделал что-то и залил это в основной код
если чтото нужно - форкай/копируй, и меняй чтото под свой проект, но не захламляй базу

если хочешь чтобы твой код добавили в основную либу
оформи код в виде модуля, который добавляет/изменяет контент либы, а также пример контента к этому модулю
]]